const constants = {
    API_FETCH_LISTS: 'API_FETCH_LISTS',
    API_ADD_LIST: 'API_ADD_LIST',
    API_DELETE_LIST: 'API_DELETE_LIST',
    API_UPDATE_LIST: 'API_UPDATE_LIST',
    UPDATE_LISTS_ON_DROP: 'UPDATE_LISTS_ON_DROP',
    ADD_CARD_TO_LIST: 'ADD_CARD_TO_LIST',


    FETCH_CARD: 'FETCH_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    UPDATE_CARD_LISTS_ON_DROP: 'UPDATE_CARD_LISTS_ON_DROP',
    UPDATE_CARD_LISTS_ON_CARD_DROP: 'UPDATE_CARD_LISTS_ON_CARD_DROP'
};

export const ROOT_URL = 'http://localhost:3000';
export default constants;
