const constants = {
    API_FETCH_LISTS: 'API_FETCH_LISTS',
    API_ADD_LIST: 'API_ADD_LIST',
    API_DELETE_LIST: 'API_DELETE_LIST',
    API_UPDATE_LIST: 'API_UPDATE_LIST',
    UPDATE_LISTS_ON_DROP: 'UPDATE_LISTS_ON_DROP',
    API_ADD_CARD_TO_LIST: 'API_ADD_CARD_TO_LIST',
    API_FETCH_CARD: 'API_FETCH_CARD',
    API_UPDATE_CARD: 'API_UPDATE_CARD',

    UPDATE_LISTS_ON_CARD_DROP: 'UPDATE_LISTS_ON_CARD_DROP'
};

export const ROOT_URL = 'http://localhost:3000';

export default constants;
